name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: name
        run: "echo name=$( grep ^name: *.cabal | cut -d ' ' -f 2 ) >> $GITHUB_OUTPUT"
      - id: version
        run: "echo version=$( grep ^version: *.cabal | cut -d ' ' -f 2 ) >> $GITHUB_OUTPUT"
    outputs:
      name: ${{ steps.name.outputs.name }}
      version: ${{ steps.version.outputs.version }}
  cabal:
    name: Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cabal check
  gild:
    name: Gild
    needs: meta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tfausak/cabal-gild-setup-action@v2
      - run: cabal-gild --input ${{ needs.meta.outputs.name }}.cabal --mode check
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: status
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v17
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: meta
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - ghc: 9.12
            os: macos-latest
          - ghc: 9.8
            os: ubuntu-latest
          - ghc: '9.10'
            os: ubuntu-latest
          - ghc: 9.12
            os: ubuntu-latest
          - ghc: 9.12
            os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artifact
      - uses: haskell/ghcup-setup@v1
        with:
          ghc: ${{ matrix.ghc }}
          cabal: latest
      - run: ghc-pkg list
      - run: cabal sdist --output-dir artifact
      - run: cabal configure --enable-documentation --flags=pedantic --haddock-for-hackage --jobs
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: cabal update
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: cabal outdated --v2-freeze-file
      - uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          path: ~/.local/state/cabal
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build --only-download
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: cp dist-newstyle/${{ needs.meta.outputs.name }}-${{ needs.meta.outputs.version }}-docs.tar.gz artifact
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ matrix.os }}-${{ matrix.ghc }}
          path: artifact.tar
  release:
    name: Release
    needs:
      - meta
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: ${{ github.sha }}-ubuntu-latest-9.12
      - run: tar --extract --file artifact.tar --verbose
      - if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: artifact/${{ needs.meta.outputs.name }}-${{ needs.meta.outputs.version }}.tar.gz
      - run: echo PUBLISH=${{ github.event_name == 'release' && '--publish' || '' }} >> $GITHUB_ENV
      - run: cabal upload $PUBLISH --token '${{ secrets.HACKAGE_TOKEN }}' artifact/${{ needs.meta.outputs.name }}-${{ needs.meta.outputs.version }}.tar.gz
      - run: cabal --http-transport=plain-http upload --documentation $PUBLISH --token '${{ secrets.HACKAGE_TOKEN }}' artifact/${{ needs.meta.outputs.name }}-${{ needs.meta.outputs.version }}-docs.tar.gz
